spring.application.name=placementhub

# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/placement_hub

# Security & JWT Secrets (Keep these private in production)
placementhub.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
placementhub.jwt.expiration=86400000

# Server Port
server.port=8080