spring.application.name=placementhub

# MongoDB Connection
spring.data.mongodb.uri=${MONGODB_URI}

# Security & JWT Secrets (Keep these private in production)
placementhub.jwt.secret=${JWT_SECRET}
placementhub.jwt.expiration=${JWT_EXPIRATION_MS}

app.frontend.url=${FRONTEND_URL}

# Server Port
server.port=${PORT:8080}